name: Triggered by set Tag

on:
  push:
    tags:        
      - setRelease-v**

jobs:
  taginfos:
    name: Print github context infos to get Tag infos
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      BASE: ${{ steps.branch.outputs.BASE}}
    steps:
      - name: Echo infos
        run: echo '${{toJSON(github)}}'
      - name: checkout source code
        uses: actions/checkout@v1
      - name: extract branch 
        id: branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-output\ name=BASE::$branch
          echo "::debug::BASE is being set to $branch"
      - name: extract version 
        id: version
        run: |
          if [[ $(grep -oP "\d+.\d+.\d+rc\d+" <<< "${{github.ref}}") ]]; then
            version=$(grep -oP "\d+.\d+.\d+rc\d+" <<< "${{github.ref}}")
          elif [[ $(grep -oP "\d+.\d+.\d+" <<< "${{github.ref}}") ]];then
            version=$(grep -oP "\d+.\d+.\d+" <<< "${{github.ref}}")
          fi
          
          echo ::set-output\ name=VERSION::$version
          echo '::debug::VERSION is being set to $version'


  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare package and set version
        run: |
          echo ${{ needs.taginfos.outputs.VERSION }} > version.txt

      - name: Create Pull Request
        if: contains(needs.taginfos.outputs.VERSION, 'rc')
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Version number for Prerelease
          title: Update Version number for RC[v${{ needs.taginfos.outputs.VERSION }}]
          body: Update Version number for RC[v${{ needs.taginfos.outputs.VERSION }}]
          branch: update-rc-version
          base: ${{ needs.taginfos.outputs.BASE }}
          token: ${{ secrets.NEOBOT_PR_PAT }}
    
      - name: Create Pull Request
        if:  ${{!contains(needs.taginfos.outputs.VERSION, 'rc')}}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Version number for Release
          title: Update Version number for [v${{ needs.taginfos.outputs.VERSION }}]
          body: Update Version number for [v${{ needs.taginfos.outputs.VERSION }}]
          branch: update-version
          base: ${{ needs.taginfos.outputs.BASE }}
          token: ${{ secrets.NEOBOT_PR_PAT }}
    